services:
  postgres:
    image: postgres:16
    command: postgres -c hba_file=/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./db/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
